Controllers/YonetimController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBlog.Models;

namespace MvcBlog.Controllers
{
    using Models;
    using MvcBlog.ayarlar;
   // [_securityFilter]

    public class YonetimController : Controller
    {
       

        Model1 db = new Model1();
        // GET: Yonetim
       
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult makaleYaz()
        {
            ViewBag.kategori = db.kategori.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult makaleYaz(makale makale,HttpPostedFileBase Resim2, string etiketler)
        {

            if (makale != null)
            {
                

                kullanici aktif = Session["Kullanici"] as kullanici;
                makale.YayinTarihi = DateTime.Now;
                makale.MakaleTipID = 1;
                makale.YazarID = aktif.Id;
                makale.KapakResimID = ResimKaydet(Resim2, HttpContext);
                db.makale.Add(makale);
                db.SaveChanges();

                string[] etikets = etiketler.Split(',');
                foreach (string etiket in etikets)
                {
                    etiket etk = db.etiket.FirstOrDefault(x => x.Ad.ToLower() == etiket.ToLower().Trim());
                    if (etk == null)
                    {
                        etk = new etiket();
                        etk.Ad = etiket;
                        db.etiket.Add(etk);
                        db.SaveChanges();
                                           
                    }
                        //etiket var
                        makale.etiket.Add(etk);
                        db.SaveChanges();                   
                }
            }            
            return RedirectToAction("MakaleListele");
        }


        public static int ResimKaydet(HttpPostedFileBase Resim,HttpContextBase ctx)
        {
            Model1 db = new Model1();
            

            kullanici k = (kullanici)ctx.Session["Kullanici"];

            int kucukWidth = Convert.ToInt32(ConfigurationManager.AppSettings["kw"]);
            int kucukHeight = Convert.ToInt32(ConfigurationManager.AppSettings["kh"]);
            int ortaWidth = Convert.ToInt32(ConfigurationManager.AppSettings["ow"]);
            int ortaHeight = Convert.ToInt32(ConfigurationManager.AppSettings["oh"]);
            int buyukWidth = Convert.ToInt32(ConfigurationManager.AppSettings["bw"]);
            int buyukHeight = Convert.ToInt32(ConfigurationManager.AppSettings["bh"]);

            string newName = Path.GetFileNameWithoutExtension(Resim.FileName)+"-" + Guid.NewGuid() + Path.GetExtension(Resim.FileName);

            Image orjRes = Image.FromStream(Resim.InputStream);
            Bitmap kucukRes = new Bitmap(orjRes, kucukWidth, kucukHeight);
            Bitmap ortaRes = new Bitmap(orjRes, ortaWidth, ortaHeight);
            Bitmap buyukRes = new Bitmap(orjRes, buyukWidth, buyukHeight);

            kucukRes.Save(ctx.Server.MapPath("~/Content/Resimler/Kucuk/" + newName));
            ortaRes.Save(ctx.Server.MapPath("~/Content/Resimler/Orta/" + newName));
            buyukRes.Save(ctx.Server.MapPath("~/Content/Resimler/Buyuk/" + newName));


            resim dbRes = new resim();
            dbRes.Ad = Resim.FileName;
            dbRes.BuyukResimYol = "/Content/Resimler/Buyuk/" + newName;
            dbRes.OrtaResimYol = "/Content/Resimler/Orta/" + newName;
            dbRes.KucukResimYol = "/Content/Resimler/Kucuk/" + newName;

            dbRes.EklenmeTarihi = DateTime.Now;
            dbRes.EkleyenID = k.Id;

            db.resim.Add(dbRes);
            db.SaveChanges();

            return dbRes.Id;

        }
        public ActionResult MakaleListele()
        {
            return View(db.makale.ToList());
        }



    }
}

Views/Yonetim/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

Views/Yonetim/MakaleListele.cshtml
@{
    ViewBag.Title = "MakaleListele";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}



@model IEnumerable<MvcBlog.Models.makale>

    
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Makaleler Tablosu</h3>

                    <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control float-right" placeholder="Ara">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0" style="height: 300px;">
                    <table class="table table-head-fixed text-nowrap">
                        <thead>
                            <tr>
                                <th>Başlık</th>
                                <th>Yazar</th>
                                <th>Kategori</th>
                                <th>Yayın Tarihi</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var m in Model)
                            {
                                <tr>
                                    <td>@m.Baslik</td>
                                    <td>@m.kullanici.Ad @m.kullanici.Soyad</td>
                                    <td>@m.kategori.Ad</td>                                   
                                    <td>@m.YayinTarihi</td>
                                </tr>
                            }



                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    

Views/Yonetim/makaleYaz.cshtml
@{
    ViewBag.Title = "makaleYaz";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

    
    <head>
        <meta charset="UTF-8">
        <title>without bootstrap</title>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    </head>

    <div class="card card-primary col-md-12">
        <div class="card-header">
            <h3 class="card-title">Kendi Makaleni Yaz</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        @using (Html.BeginForm("makaleYaz", "Yonetim", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="card-body">

                <!-- Başlık Kısmı -->
                <div class="form-group">
                    <label>Makale Başlığını Giriniz</label>
                    <input type="text" name="Baslik"  class="form-control" placeholder="Başlığınız ...">
                </div>

                <div class="form-group">
                    <label>Kategori</label>
                    <select class="form-control" name="KategoriID">
                        @foreach (var kategori in ViewBag.kategori)
                        {
                            <option value="@kategori.Id">@kategori.Ad</option>

                        }
                    </select>
                </div>

                <!-- Etiket Kısmı -->
                <div class="form-group">
                    <label>Etiketler</label>
                    <input type="text" name="etiketler" class="form-control" placeholder="Etiket Giriniz ...">
                </div>

                <!-- Resim ekleme Kısmı -->
                <div class="form-group">
                    <label for="exampleInputFile">Resminizi Seçiniz </label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-control" name="Resim2" id="exampleInputFile" value="" />
                            <label class="" for="exampleInputFile"></label>
                        </div>
                    </div>
                </div>
                <!-- içerik Kısmı -->
                <div class="form-group">
                    <label>İçerik</label>
                    <textarea class="form-control" id="summernote2" name="Icerik" rows="30" placeholder="İçeriğinizi yazınız ..."></textarea>
                </div>




            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Kaydet</button>
            </div>

        }
         

        @*<form role="form">
        </form>*@
    </div>

   
    <script>
        $('#summernote2').summernote({
            placeholder: 'Hello stand alone ui',
            tabsize: 2,
            height: 120,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'video']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ]
        });
    </script>

  
    <script>
        $('#summernote').summernote({
            placeholder: 'Hello stand alone ui',
            tabsize: 2,
            height: 120,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'video']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ]
        });
    </script>